// GENERADO por scripts/genera-hoteles.py — no editar a mano.
// Instantanea de `haa.hotel` (Odoo de produccion) del 2026-08-25.
// Es la red del selector de hotel del funnel: lo que se pinta mientras
// llega `/hotels` y lo que queda si Odoo no contesta. Para refrescarla,
// volver a correr el script con el volcado de la base.

import type { Hotel } from '@/lib/api/tipos'

export const HOTELES: Hotel[] = [
  { id: 24, name: 'AC Hotel by Marriott', zone: 'Bavaro' },
  { id: 183, name: 'Alisios Bavaro', zone: 'Bavaro' },
  { id: 23, name: 'Ancora Cap Cana', zone: 'Bavaro' },
  { id: 25, name: 'Apartamentos Florisel', zone: 'Bavaro' },
  { id: 26, name: 'Aqua Marina Cap Cana', zone: 'Bavaro' },
  { id: 40, name: 'Bahia P. Escape Aquario', zone: 'Bavaro' },
  { id: 33, name: 'BAHIA P. PUNTA CANA', zone: 'Bavaro' },
  { id: 141, name: 'Bahia Principe Bavaro', zone: 'Bavaro' },
  { id: 46, name: 'Bahia Principe Bavaro Entrance Gate to Resort', zone: 'Bavaro' },
  { id: 157, name: 'Bahia Principe Bavaro Main Gate', zone: 'Bavaro' },
  { id: 177, name: 'Bahia Principe Escape Ambar', zone: 'Bavaro' },
  { id: 155, name: 'Bahia Principe Escape Ambar Bahia Prin', zone: 'Bavaro' },
  { id: 212, name: 'Bahia Principe Escape Ambar Bahia Principe Aquamarine', zone: 'Bavaro' },
  { id: 142, name: 'Bahia Principe Escape Ambar Bahia Principe Bavaro', zone: 'Bavaro' },
  { id: 47, name: 'Bahia Principe Escape Ambar Entrance Gate to Resort', zone: 'Bavaro' },
  { id: 158, name: 'Bahia Principe Escape Ambar Main Gate', zone: 'Bavaro' },
  { id: 159, name: 'Bahia Principe Escape Aquamarine', zone: 'Bavaro' },
  { id: 178, name: 'Bahia Principe Explore Esmeralda', zone: 'Bavaro' },
  { id: 143, name: 'Bahia Principe Explore Esmeralda Bahia Principe Punta Cana', zone: 'Bavaro' },
  { id: 48, name: 'Bahia Principe Explore Esmeralda Entrance Gate to Resort', zone: 'Bavaro' },
  { id: 160, name: 'Bahia Principe Explore Esmeralda Main Gate', zone: 'Bavaro' },
  { id: 226, name: 'Bahia Principe Explore Legend', zone: 'Bavaro' },
  { id: 144, name: 'Bahia Principe Explore Punta Cana', zone: 'Bavaro' },
  { id: 49, name: 'Bahia Principe Explore Punta Cana Entrance Gate to Resort', zone: 'Bavaro' },
  { id: 161, name: 'Bahia Principe Explore Punta Cana Main Gate', zone: 'Bavaro' },
  { id: 145, name: 'Bahia Principe Explore Turquesa', zone: 'Bavaro' },
  { id: 50, name: 'Bahia Principe Explore Turquesa Entrance Gate to Resort', zone: 'Bavaro' },
  { id: 162, name: 'Bahia Principe Explore Turquesa Main Gate', zone: 'Bavaro' },
  { id: 146, name: 'Bahia Principe Fantasia', zone: 'Bavaro' },
  { id: 51, name: 'Bahia Principe Fantasia Entrance Gate to Resort', zone: 'Bavaro' },
  { id: 163, name: 'Bahia Principe Fantasia Main Gate', zone: 'Bavaro' },
  { id: 147, name: 'Bahia Principe Premier', zone: 'Bavaro' },
  { id: 52, name: 'Bahia Principe Premier Entrance Gate to Resort', zone: 'Bavaro' },
  { id: 164, name: 'Bahia Principe Premier Main Gate', zone: 'Bavaro' },
  { id: 53, name: 'Barcelo Bavaro Beach', zone: 'Bavaro' },
  { id: 4, name: 'Barcelo Bavaro Palace', zone: 'Bavaro' },
  { id: 54, name: 'Barcelo Family Deluxe', zone: 'Bavaro' },
  { id: 55, name: 'Barcelo Palace Deluxe', zone: 'Bavaro' },
  { id: 184, name: 'Bavaro Hotel', zone: 'Bavaro' },
  { id: 56, name: 'Bavaro Princess', zone: 'Bavaro' },
  { id: 185, name: 'Be Live Collection ADULTS ONLY', zone: 'Bavaro' },
  { id: 57, name: 'Blue Beach Punta Cana', zone: 'Bavaro' },
  { id: 231, name: 'BlueBay Grand', zone: 'Bavaro' },
  { id: 6, name: 'Breathless Punta Cana', zone: 'Bavaro' },
  { id: 232, name: 'Cana Rock Condos', zone: 'Bavaro' },
  { id: 58, name: 'Caribe Club Princess', zone: 'Bavaro' },
  { id: 213, name: 'Caribe Deluxe Princess', zone: 'Bavaro' },
  { id: 59, name: 'Catalonia Bavaro Beach', zone: 'Bavaro' },
  { id: 171, name: 'Catalonia Punta Cana', zone: 'Bavaro' },
  { id: 60, name: 'Catalonia Royal Bavaro', zone: 'Bavaro' },
  { id: 148, name: 'Chateau del Mar', zone: 'Bavaro' },
  { id: 233, name: 'Coral Bay Punta Cana', zone: 'Bavaro' },
  { id: 186, name: 'Coral Level at Iberostar Bavaro', zone: 'Bavaro' },
  { id: 234, name: 'Cortecito Inn', zone: 'Bavaro' },
  { id: 235, name: 'Costa Atlantica', zone: 'Bavaro' },
  { id: 165, name: 'Dreams Flora Resort', zone: 'Bavaro' },
  { id: 21, name: 'Dreams Macao Beach', zone: 'Bavaro' },
  { id: 236, name: 'Dreams Palm Beach', zone: 'Bavaro' },
  { id: 11, name: 'Dreams Royal Beach', zone: 'Bavaro' },
  { id: 61, name: 'Dreams Royal Beach Punta Cana', zone: 'Bavaro' },
  { id: 1, name: 'Excellence Punta Cana', zone: 'Bavaro' },
  { id: 62, name: 'Falcon Resort by Melia', zone: 'Bavaro' },
  { id: 237, name: 'Faranda Single 1 Punta Cana', zone: 'Bavaro' },
  { id: 43, name: 'fdlkjsdafdfsdfdsf', zone: 'Bavaro' },
  { id: 238, name: 'Flamboyan', zone: 'Bavaro' },
  { id: 41, name: 'Garden Suites by Melia', zone: 'Bavaro' },
  { id: 22, name: 'Grand Bavaro Princess', zone: 'Bavaro' },
  { id: 63, name: 'Grand Palladium Bavaro', zone: 'Bavaro' },
  { id: 64, name: 'Grand Palladium Palace', zone: 'Bavaro' },
  { id: 65, name: 'Grand Palladium Punta Cana', zone: 'Bavaro' },
  { id: 66, name: 'Grand Palladium Royal Turquesa', zone: 'Bavaro' },
  { id: 67, name: 'Grand Paradise', zone: 'Bavaro' },
  { id: 68, name: 'Grand Reserve at Melia', zone: 'Bavaro' },
  { id: 202, name: 'Green Coast Beach', zone: 'Bavaro' },
  { id: 239, name: 'Green Coast Hotel', zone: 'Bavaro' },
  { id: 187, name: 'Hard Rock Hotel', zone: 'Bavaro' },
  { id: 3, name: 'Hard Rock Hotel & Casino', zone: 'Bavaro' },
  { id: 69, name: 'Hard Rock Hotel GROUP Lobby', zone: 'Bavaro' },
  { id: 166, name: 'Hard Rock Hotel Hard Rock GROUP lobby', zone: 'Bavaro' },
  { id: 149, name: 'Hard Rock Hotel Hotel Hard Rock GROUP lo', zone: 'Bavaro' },
  { id: 241, name: 'HM Bavaro Beach', zone: 'Bavaro' },
  { id: 42, name: 'Hotel de prueba', zone: 'Bavaro' },
  { id: 242, name: 'Hotel MT Plaza Brisas', zone: 'Bavaro' },
  { id: 45, name: 'Hotel Nom', zone: 'Bavaro' },
  { id: 44, name: 'Hotel x', zone: 'Bavaro' },
  { id: 243, name: 'Hyatt Vivid Punta Cana', zone: 'Bavaro' },
  { id: 70, name: 'Iberostar Bavaro', zone: 'Bavaro' },
  { id: 71, name: 'Iberostar Dominicana', zone: 'Bavaro' },
  { id: 7, name: 'Iberostar Grand Bavaro', zone: 'Bavaro' },
  { id: 72, name: 'Iberostar Punta Cana', zone: 'Bavaro' },
  { id: 36, name: 'IBEROSTAR SELECTION', zone: 'Bavaro' },
  { id: 244, name: 'Iberostar Selection Bavaro Suites', zone: 'Bavaro' },
  { id: 221, name: 'IFA Villas Bavaro Resort', zone: 'Bavaro' },
  { id: 73, name: 'Impressive Resorts & Spa Punta Cana', zone: 'Bavaro' },
  { id: 74, name: 'Jewel Palm Beach', zone: 'Bavaro' },
  { id: 35, name: 'JOIA BAVARO BY IBERI', zone: 'Bavaro' },
  { id: 75, name: 'JOIA Bavaro by Iberostar', zone: 'Bavaro' },
  { id: 76, name: 'Karibo Punta Cana', zone: 'Bavaro' },
  { id: 222, name: 'Karimar Bavaro', zone: 'Bavaro' },
  { id: 9, name: 'Lopesan Costa Bavaro', zone: 'Bavaro' },
  { id: 203, name: 'Lopesan Costa Bavaro meeting point', zone: 'Bavaro' },
  { id: 245, name: 'Los Corales Punta Cana', zone: 'Bavaro' },
  { id: 150, name: 'Los Corales Village', zone: 'Bavaro' },
  { id: 204, name: 'Los Corales Village Main Gate in front Angelos P 8:40 AM', zone: 'Bavaro' },
  { id: 188, name: 'Luxury Bahia Principe Ambar', zone: 'Bavaro' },
  { id: 214, name: 'Luxury Bahia Principe Ambar Bahia Principe Aquamarine 8:25 AM', zone: 'Bavaro' },
  { id: 151, name: 'Luxury Bahia Principe Ambar bahia principe bavaro', zone: 'Bavaro' },
  { id: 77, name: 'Luxury Bahia Principe Ambar Main Gate', zone: 'Bavaro' },
  { id: 78, name: 'Majestic Colonial', zone: 'Bavaro' },
  { id: 12, name: 'Majestic Elegance', zone: 'Bavaro' },
  { id: 29, name: 'MAJESTIC ELEGANCE PUNTA CANA', zone: 'Bavaro' },
  { id: 32, name: 'Majestic Elegance Punta Cana All Inclusive', zone: 'Bavaro' },
  { id: 37, name: 'MAJESTIC MIRAGE PUNTA CANA', zone: 'Bavaro' },
  { id: 189, name: 'Manaca Bed & Breakfast', zone: 'Bavaro' },
  { id: 34, name: 'Melia Caribe Beach', zone: 'Bavaro' },
  { id: 205, name: 'Melia Caribe Beach lobby', zone: 'Bavaro' },
  { id: 79, name: 'Melia Caribe Beach Melia Punta Cana Beach', zone: 'Bavaro' },
  { id: 80, name: 'Melia Punta Cana Beach', zone: 'Bavaro' },
  { id: 206, name: 'Melia Punta Cana Beach lobby', zone: 'Bavaro' },
  { id: 81, name: 'Memories Splash Punta Cana', zone: 'Bavaro' },
  { id: 207, name: 'Memories Splash Punta Cana main gate', zone: 'Bavaro' },
  { id: 247, name: 'Moon Place Punta Cana', zone: 'Bavaro' },
  { id: 82, name: 'Natura Park Eco Park', zone: 'Bavaro' },
  { id: 83, name: 'NH Punta Cana', zone: 'Bavaro' },
  { id: 84, name: 'NOW Garden Punta Cana', zone: 'Bavaro' },
  { id: 85, name: 'NOW Larimar', zone: 'Bavaro' },
  { id: 10, name: 'Now Onyx', zone: 'Bavaro' },
  { id: 86, name: 'Occidental Caribe', zone: 'Bavaro' },
  { id: 87, name: 'Occidental Grand', zone: 'Bavaro' },
  { id: 172, name: 'Occidental Punta Cana', zone: 'Bavaro' },
  { id: 88, name: 'Ocean Blue & Sands', zone: 'Bavaro' },
  { id: 38, name: 'OCEAN EL FARO', zone: 'Bavaro' },
  { id: 215, name: 'Paradisus Grand Cana', zone: 'Bavaro' },
  { id: 5, name: 'Paradisus Palma Real', zone: 'Bavaro' },
  { id: 89, name: 'Paradisus Palma Real The Reserve', zone: 'Bavaro' },
  { id: 90, name: 'Paradisus Punta Cana', zone: 'Bavaro' },
  { id: 91, name: 'Paradisus Punta Cana The Reserve', zone: 'Bavaro' },
  { id: 208, name: 'Playa Coral by Noval', zone: 'Bavaro' },
  { id: 92, name: 'Playa Turquesa Condo', zone: 'Bavaro' },
  { id: 93, name: 'Presidential Suites Bavaro', zone: 'Bavaro' },
  { id: 248, name: 'Princess Family Club Bavaro', zone: 'Bavaro' },
  { id: 94, name: 'Punta Cana Princess', zone: 'Bavaro' },
  { id: 190, name: 'Radisson Blu', zone: 'Bavaro' },
  { id: 28, name: 'RIU Bambu', zone: 'Bavaro' },
  { id: 95, name: 'RIU Naiboa', zone: 'Bavaro' },
  { id: 96, name: 'RIU Palace Bavaro', zone: 'Bavaro' },
  { id: 97, name: 'RIU Palace Macao', zone: 'Bavaro' },
  { id: 98, name: 'RIU Palace Punta Cana', zone: 'Bavaro' },
  { id: 13, name: 'Riu Republica', zone: 'Bavaro' },
  { id: 249, name: 'Riviera Punta Cana Eco-Travelers House', zone: 'Bavaro' },
  { id: 99, name: 'Royalton Bavaro', zone: 'Bavaro' },
  { id: 179, name: 'Royalton Bavaro MAIN ENTRANCE', zone: 'Bavaro' },
  { id: 216, name: 'Royalton Bavaro main gate (outside)', zone: 'Bavaro' },
  { id: 209, name: 'Royalton Bavaro outside', zone: 'Bavaro' },
  { id: 8, name: 'Royalton Punta Cana', zone: 'Bavaro' },
  { id: 180, name: 'Royalton Punta Cana MAIN ENTRANCE', zone: 'Bavaro' },
  { id: 217, name: 'Royalton Punta Cana main gate (outside)', zone: 'Bavaro' },
  { id: 210, name: 'Royalton Punta Cana outside', zone: 'Bavaro' },
  { id: 211, name: 'Royalton Splash Punta Cana', zone: 'Bavaro' },
  { id: 274, name: 'Royalton Splash Punta Cana MAIN ENTRANCE', zone: 'Bavaro' },
  { id: 218, name: 'Royalton Splash Punta Cana main gate (outside)', zone: 'Bavaro' },
  { id: 30, name: 'Sanctuary Cap Cana by Alsol', zone: 'Bavaro' },
  { id: 250, name: 'Sea Dreams Residence', zone: 'Bavaro' },
  { id: 100, name: 'Secrets Royal Beach', zone: 'Bavaro' },
  { id: 2, name: 'Secrets Tides', zone: 'Bavaro' },
  { id: 182, name: 'Sensimar Bavaro', zone: 'Bavaro' },
  { id: 31, name: 'Serenade All Suites', zone: 'Bavaro' },
  { id: 39, name: 'Serenade All Suites, Adults Only', zone: 'Bavaro' },
  { id: 167, name: 'Serenade Beach Resort', zone: 'Bavaro' },
  { id: 27, name: 'SERENADE PUNTA CANA BEACH & SPA RESORT', zone: 'Bavaro' },
  { id: 251, name: 'Sol Caribe - El Cortecito', zone: 'Bavaro' },
  { id: 101, name: 'Stanza Mare', zone: 'Bavaro' },
  { id: 102, name: 'Sunscape Coco Punta Cana', zone: 'Bavaro' },
  { id: 103, name: 'Sunscape Dominican Beach', zone: 'Bavaro' },
  { id: 252, name: 'Total Energie Plaza Downtown (KFC)', zone: 'Bavaro' },
  { id: 104, name: 'Tropical Bavaro Clubs', zone: 'Bavaro' },
  { id: 253, name: 'Tropical Deluxe Princess', zone: 'Bavaro' },
  { id: 105, name: 'Tropical Princess', zone: 'Bavaro' },
  { id: 168, name: 'TRS Turquesa Hotel', zone: 'Bavaro' },
  { id: 106, name: 'Vik Arena Blanca', zone: 'Bavaro' },
  { id: 107, name: 'VIK Cayena Beach Club', zone: 'Bavaro' },
  { id: 254, name: 'Vista Cana', zone: 'Bavaro' },
  { id: 108, name: 'Vista Sol Punta Cana', zone: 'Bavaro' },
  { id: 109, name: 'Whala Bavaro', zone: 'Bavaro' },
  { id: 169, name: 'Whala Urban', zone: 'Bavaro' },
  { id: 255, name: 'Xeliter Cana Rock Punta Cana', zone: 'Bavaro' },
  { id: 256, name: 'Zel Punta Cana', zone: 'Bavaro' },
  { id: 110, name: 'ALSOL Del Mar', zone: 'Punta Cana' },
  { id: 111, name: 'ALSOL Luxury Village', zone: 'Punta Cana' },
  { id: 112, name: 'ALSOL Sanctuary Cap Cana', zone: 'Punta Cana' },
  { id: 113, name: 'ALSOL Tiara', zone: 'Punta Cana' },
  { id: 152, name: 'Aqua Marina Cap Cana Aquamarina Main lobby', zone: 'Punta Cana' },
  { id: 257, name: 'Azul Beach Resort', zone: 'Punta Cana' },
  { id: 114, name: 'Caleton Villas', zone: 'Punta Cana' },
  { id: 173, name: 'Cana Rock Space', zone: 'Punta Cana' },
  { id: 174, name: 'Cana Rock Terra', zone: 'Punta Cana' },
  { id: 219, name: 'Cap Cana Aquamarina', zone: 'Punta Cana' },
  { id: 153, name: 'Club Med', zone: 'Punta Cana' },
  { id: 115, name: 'Club Med Main gate', zone: 'Punta Cana' },
  { id: 19, name: 'Club Med Punta Cana', zone: 'Punta Cana' },
  { id: 258, name: 'Del Mar by Joy Resorts', zone: 'Punta Cana' },
  { id: 175, name: 'Dreams Cap Cana', zone: 'Punta Cana' },
  { id: 116, name: 'Eden Roc at Cap Cana', zone: 'Punta Cana' },
  { id: 117, name: 'Fishing Lodge Cap Cana', zone: 'Punta Cana' },
  { id: 118, name: 'Four Points Punta Cana', zone: 'Punta Cana' },
  { id: 259, name: 'Four Seasons Cap Cana', zone: 'Punta Cana' },
  { id: 119, name: 'Golden Bear Lodge', zone: 'Punta Cana' },
  { id: 120, name: 'Hyatt Ziva Cap Cana', zone: 'Punta Cana' },
  { id: 260, name: 'La Arboleda Lodge', zone: 'Punta Cana' },
  { id: 261, name: 'Margaritaville Island Reserve', zone: 'Punta Cana' },
  { id: 121, name: 'Marina Sands Luxury Resort', zone: 'Punta Cana' },
  { id: 122, name: 'Punta Cana Resort & Club', zone: 'Punta Cana' },
  { id: 154, name: 'Punta Palmera Cap Cana', zone: 'Punta Cana' },
  { id: 123, name: 'Soto Grande', zone: 'Punta Cana' },
  { id: 220, name: 'Sports Illustrated Resorts Marina', zone: 'Punta Cana' },
  { id: 262, name: 'Tanama Lodge', zone: 'Punta Cana' },
  { id: 17, name: 'The Westin Puntacana', zone: 'Punta Cana' },
  { id: 18, name: 'Tortuga Bay', zone: 'Punta Cana' },
  { id: 124, name: 'Tortuga Bay Hotel', zone: 'Punta Cana' },
  { id: 125, name: 'Tortuga Bay Villas', zone: 'Punta Cana' },
  { id: 126, name: 'TRS Cap Cana', zone: 'Punta Cana' },
  { id: 127, name: 'Westin Punta Cana', zone: 'Punta Cana' },
  { id: 176, name: 'Yarari Villa in Cap Cana', zone: 'Punta Cana' },
  { id: 15, name: 'Hyatt Zilara Cap Cana', zone: 'Cap Cana' },
  { id: 16, name: 'Sanctuary Cap Cana', zone: 'Cap Cana' },
  { id: 14, name: 'Secrets Cap Cana', zone: 'Cap Cana' },
  { id: 128, name: 'Dreams Onyx Resort & Spa', zone: 'Uvero Alto' },
  { id: 263, name: 'Dreams Punta Cana', zone: 'Uvero Alto' },
  { id: 129, name: 'Excellence El Carmen', zone: 'Uvero Alto' },
  { id: 170, name: 'Finest Punta Cana', zone: 'Uvero Alto' },
  { id: 130, name: 'Grand Sirenis Aqua Games', zone: 'Uvero Alto' },
  { id: 131, name: 'Grand Sirenis Punta Cana', zone: 'Uvero Alto' },
  { id: 132, name: 'Jewel Punta Cana', zone: 'Uvero Alto' },
  { id: 133, name: 'Le Sivory Punta Cana by Portblue', zone: 'Uvero Alto' },
  { id: 134, name: 'Live Aqua Beach Resort Punta Cana', zone: 'Uvero Alto' },
  { id: 135, name: 'Nickelodeon', zone: 'Uvero Alto' },
  { id: 20, name: 'Nickelodeon Hotels & Resorts', zone: 'Uvero Alto' },
  { id: 264, name: 'Playa Palmera', zone: 'Uvero Alto' },
  { id: 136, name: 'Royalton Chic Punta Cana', zone: 'Uvero Alto' },
  { id: 181, name: 'Royalton Chic Punta Cana MAIN ENTRANCE', zone: 'Uvero Alto' },
  { id: 137, name: 'Sensatori', zone: 'Uvero Alto' },
  { id: 138, name: 'Sensimar Punta Cana', zone: 'Uvero Alto' },
  { id: 139, name: 'Sirenis Cocotal', zone: 'Uvero Alto' },
  { id: 265, name: 'W Punta Cana', zone: 'Uvero Alto' },
  { id: 266, name: 'Wyndham Alltra Punta Cana', zone: 'Uvero Alto' },
  { id: 140, name: 'Zoetry Aqua Punta Cana', zone: 'Uvero Alto' },
  { id: 276, name: 'Aqua Esmeralda', zone: 'Bayahibe' },
  { id: 191, name: 'Be Live Canoa', zone: 'Bayahibe' },
  { id: 192, name: 'Cadaques Bayahibe', zone: 'Bayahibe' },
  { id: 277, name: 'Catalonia Bayahibe', zone: 'Bayahibe' },
  { id: 193, name: 'Catalonia Gran Dominicus', zone: 'Bayahibe' },
  { id: 278, name: 'Catalonia Royal La Romana', zone: 'Bayahibe' },
  { id: 194, name: 'Dreams Dominicus La Romana', zone: 'Bayahibe' },
  { id: 195, name: 'Dreams La Romana', zone: 'Bayahibe' },
  { id: 279, name: 'Estrella Dominicus', zone: 'Bayahibe' },
  { id: 280, name: 'HM Alma de Bayahibe', zone: 'Bayahibe' },
  { id: 281, name: 'Hotel Palmera', zone: 'Bayahibe' },
  { id: 196, name: 'Iberostar Hacienda Dominicus', zone: 'Bayahibe' },
  { id: 197, name: 'Los Flamencos', zone: 'Bayahibe' },
  { id: 282, name: 'Secrets La Romana', zone: 'Bayahibe' },
  { id: 283, name: 'Soficu On The Beach', zone: 'Bayahibe' },
  { id: 284, name: 'Sunscape Dominicus La Romana', zone: 'Bayahibe' },
  { id: 198, name: 'Tracadero Beach Resort', zone: 'Bayahibe' },
  { id: 199, name: 'Viva Dominicus Beach', zone: 'Bayahibe' },
  { id: 200, name: 'Viva Dominicus Palace', zone: 'Bayahibe' },
  { id: 201, name: 'Whala Bayahibe', zone: 'Bayahibe' },
  { id: 156, name: 'Dreams Macao Beach Punta Cana', zone: 'Macao' },
]
